---
- name: Create Logstash configuration files.
  template:
    src: "log.conf.j2"
    dest: "/etc/logstash/conf.d/{{ item.key }}.conf"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ log_files }}"
  notify: restart logstash
